files:
  - source: Base.lproj/*Help?.plist
    translation: /%two_letters_code%.lproj/%original_file_name%
  - source: Base.lproj/Localizable.strings
    translation: /%two_letters_code%.lproj/%original_file_name%
